---
title: "FIT Challenge"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r libraries, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(gridExtra)
library(ggthemes)
library(scales)
library(zoo)
library(knitr)
library(kableExtra)
library(RColorBrewer)
library(toOrdinal)
library(shiny)
library(DT)
library(rsconnect)
library(pdftools)
library(httr)
library(RCurl)
library(lubridate)

rsconnect::setAccountInfo(name='robdaslob',
			  token='77DFD7FDDE2622091A2CE41C3C40620B',
			  secret='galxFmxQG+p05eH2jL11TafNmPbw7K2Wc7Zo3Egi')


```


```{r ExtractData ,include=FALSE}

## Reading in pdf
## Honestly, this section would be much faster if you copied directly from pdf to a file and read that file in
## Just want to get experience working with pdf's
## Make sure you have the correct working directory
PdfName <- "San_Diego_Detailed_Results_Spring_2019_Challenge.pdf"

## Reading the fifth page (i.e. Course 1 - Level 2)
## Should probably turn this and the following into a function since you're calling same functions in multiple spots
## Also should try to read more than one page at a time
## This code should definitely be improved
RawPageFive <- pdf_text(PdfName)[[5]] %>%
  readr::read_lines()

## Taking the rows that have ICW in it
## Could make this dynamic
Course1IcwStats <- RawPageFive[str_detect(RawPageFive ,pattern = 'ICW Group')] %>%
  str_squish()

## Team Names
## Should probably be general in case ppl leave
TeamName <- tibble(
  TeamId = c(1 ,2)
  ,EventNumber = c("2019-1" ,"2019-1")
  ,BibNumber = c(3099 ,3100)
  ,TeamName = c("Data Squad" ,"Team Taylor")
)

## Exercise Number
## Just used for ordering purposes
ExerciseTable <- tibble(
  ExerciseId = c(1:12)
  ,Exercise = c("InvertedRows" ,"LebertPlankHops" ,"PushUps" ,"KettlebellSwings" ,"SandbagCrunchToss" ,"Burpees" ,"PlankHold" ,"AgilityRelay" ,"FullBodyConditioning" ,"RopePullRelay" ,"ParachuteRelay" ,"Laps")
)

## Should probably keep record of the players too
## Maybe can have some filter for ppl to only show the events they competed in
PlayersTable <- tibble(
  PlayerId = c(1:8)
  ,TeamId = c(rep(1,4) ,rep(2,4))
  ,EventId = c(rep(1,8))
  ## Double check the spelling on these
  ## Think some of them are probably off
  ,PlayerName = c("Akshit Bhatnagar" ,"Chris Smith" ,"Eric Freiberg" ,"Monora Seth" ,"Taylor Robinson" ,"David Cunningham" ,"RoBert RiesenBerg" ,"Kaleb Hite")
)

## Just adding in first / last name columns
## Can probably just use these if ppl don't have same names
PlayersTable %>%
  mutate(FirstName = str_trim(str_extract(PlayerName ,pattern = ".* "))
         ,LastName = str_trim(str_extract(PlayerName ,pattern = " .*$")))

## Coercing data into necessary format
## Should probably make this more dynamic rather than hardcoding names & positions of reps
Course1Data <- Course1IcwStats %>%
  str_extract_all(pattern = "[0-9]+") %>%
  tibble(
    EventId = 1
    ,EventNumber = "2019-1"
    ,Course = "Course 1"
    ,Level = "Level 2"
    ,BibNumber = map_chr(. ,1) %>% as.numeric()
    ,InvertedRows = map_chr(. ,3) %>% as.numeric()
    ,LebertPlankHops = map_chr(. ,5) %>% as.numeric()
    ,PushUps = map_chr(. ,7) %>% as.numeric()
    ,KettlebellSwings = map_chr(. ,9) %>% as.numeric()
    ,SandbagCrunchToss = map_chr(. ,11) %>% as.numeric()
    ,Burpees = map_chr(. ,13) %>% as.numeric()
    ,PlankHold = str_c(map_chr(. ,15) ," min " ,map_chr(. ,16) ," sec") %>% lubridate::ms()
  ) %>%
  select(EventId:PlankHold)


## Both teams were mistakenly put on the Level 1 page for Course 2 (even though both did level 2)
RawPageSeven <- pdf_text(PdfName)[[7]] %>%
  readr::read_lines()

## Extracting the info from Level 1 page
Course2IcwStats <- RawPageSeven[str_detect(RawPageSeven ,pattern = 'ICW Group')] %>%
  str_squish()
  
## Getting the data into a usable format
Course2Data <- Course2IcwStats %>%
  str_extract_all(pattern = "[0-9]+") %>%
  tibble(
    EventId = 1
    ,EventNumber = "2019-1"
    ,Course = "Course 2"
    ,Level = "Level 2"
    ,BibNumber = map_chr(. ,1) %>% as.numeric()
    ,AgilityRelay = str_c(map_chr(. ,3) ," min " ,map_chr(. ,4) ," sec") %>% lubridate::ms()
    ,FullBodyConditioning = str_c(map_chr(. ,6) ," min " ,map_chr(. ,7) ," sec") %>% lubridate::ms()
    ,RopePullRelay = str_c(map_chr(. ,9) ," min " ,map_chr(. ,10) ," sec") %>% lubridate::ms()
    ,ParachuteRelay = str_c(map_chr(. ,12) ," min " ,map_chr(. ,13) ," sec") %>% lubridate::ms()
  ) %>%
  select(EventId:ParachuteRelay)

## One team did level 1 exercises, the other did level 2 for Course 3
## Extracting level 1 first
RawPageEleven <- pdf_text(PdfName)[[11]] %>%
  readr::read_lines()

## Extracting the info from Level 1 page
Course3Level1IcwStats <- RawPageEleven[str_detect(RawPageEleven ,pattern = 'ICW Group')] %>%
  str_squish()
  
## Getting the data into a usable format
Course3Level1Data <- Course3Level1IcwStats %>%
  str_extract_all(pattern = "[0-9]+") %>%
  tibble(
    EventId = 1
    ,EventNumber = "2019-1"
    ,Course = "Course 3"
    ,Level = "Level 1"
    ,BibNumber = map_chr(. ,1) %>% as.numeric()
    ,Laps = map_chr(. ,3)
  ) %>%
  select(EventId:Laps)

## Doing same thing for level 2
RawPageTwelve <- pdf_text(PdfName)[[12]] %>%
  readr::read_lines()

## Extracting the info from Level 1 page
Course3Level2IcwStats <- RawPageTwelve[str_detect(RawPageTwelve ,pattern = 'ICW Group')] %>%
  str_squish()
  
## Getting the data into a usable format
Course3Level2Data <- Course3Level2IcwStats %>%
  str_extract_all(pattern = "[0-9]+") %>%
  tibble(
    EventId = 1
    ,EventNumber = "2019-1"
    ,Course = "Course 3"
    ,Level = "Level 2"
    ,BibNumber = map_chr(. ,1) %>% as.numeric()
    ,Laps = map_chr(. ,3)
  ) %>%
  select(EventId:Laps)

## Getting the data into a standard format
Course1Reps <- Course1Data %>%
  select(EventId:Burpees) %>%
  gather(key = "Exercise" ,value = "Reps" ,InvertedRows:Burpees)
Course1Timed <- Course1Data %>%
  select(EventId:BibNumber ,PlankHold) %>%
  gather(key = "Exercise" ,value = "Time" ,PlankHold) %>%
  mutate(Time = as.character(Time))
Course2Timed <- Course2Data %>%
  mutate_if(lubridate::is.period ,as.character) %>%
  gather(key = "Exercise" ,value = "Time" ,AgilityRelay:ParachuteRelay)
Course3Level1Reps <- Course3Level1Data %>%
  gather(key = "Exercise" ,value = "Reps" ,Laps) %>%
  mutate(Reps = as.numeric(Reps))
Course3Level2Reps <- Course3Level2Data %>%
  gather(key = "Exercise" ,value = "Reps" ,Laps) %>%
  mutate(Reps = as.numeric(Reps))

## Bind the Reps & Timed datasets together
CourseReps <- bind_rows(Course1Reps ,Course3Level1Reps ,Course3Level2Reps)
CourseTimed <- bind_rows(Course1Timed ,Course2Timed)

## Filtering to just the two teams that did level 2 stuff 
## More teams can be extracted and added
## I just don't know the Bibnumber to participant mapping for level 1 teams
CourseReps <- CourseReps %>%
  inner_join(TeamName ,by = c("EventNumber" ,"BibNumber"))
CourseTimed <- CourseTimed %>%
  inner_join(TeamName ,by = c("EventNumber" ,"BibNumber"))

## Converting time back to periods from character
CourseTimed <- CourseTimed %>%
  mutate(Time = lubridate::period(Time)
         ,TimeInSeconds = lubridate::period_to_seconds(Time))

## High Rep Exercises
HighRepExercises <- c("LebertPlankHops" ,"PushUps" ,"KettlebellSwings" ,"SandbagCrunchToss")

## Lower Rep Exercises 
LowRepExercises <- c("InvertedRows" ,"Burpees")

## Faster Exercises
FasterExercises <- c("AgilityRelay" ,"FullBodyConditioning" ,"RopePullRelay" ,"ParachuteRelay")

## Slower Exercises
SlowerExercises <- c("PlankHold")

## Running Exercises
RunningExercises <- c("Laps")

## Getting the max ranges for the charts
MaxHighRep <- CourseReps %>%
  filter(Exercise %in% HighRepExercises) %>%
  summarise(MaxReps = max(Reps)) %>%
  as.numeric()
MaxLowRep <- CourseReps %>%
  filter(Exercise %in% LowRepExercises) %>%
  summarise(MaxReps = max(Reps)) %>%
  as.numeric()
MaxTimeInSeconds <- CourseTimed %>%
  select(-Time) %>%
  filter(Exercise != 'PlankHold') %>%
  summarise(MaxTime = max(TimeInSeconds)) %>%
  as.numeric()
MaxLaps <- CourseReps %>%
  filter(Exercise %in% RunningExercises) %>%
  summarise(MaxReps = max(Reps)) %>%
  as.numeric()

## Getting data for the best performance table
## Need to convert to character so that the minutes seconds format can be used
BestCourseTimed <- CourseTimed %>%
  group_by(TeamName ,Exercise) %>%
  summarise(BestPerformance = min(TimeInSeconds)) %>%
  ungroup() %>%
  right_join(CourseTimed %>% mutate(Time = as.character(Time)) ,by = c("TeamName" ,"Exercise")) %>%
  select(TeamName:Exercise ,Course ,Time) %>%
  rename(BestPerformance = Time)
BestCourseReps <- CourseReps %>%
  group_by(TeamName ,Exercise) %>%
  summarise(BestPerformance = max(Reps)) %>%
  ungroup() %>%
  right_join(CourseReps %>% mutate(Reps = as.character(Reps)) ,by = c("TeamName" ,"Exercise")) %>%
  select(TeamName:Exercise ,Course ,Reps) %>%
  rename(BestPerformance = Reps)
BestPerformance <- bind_rows(BestCourseTimed ,BestCourseReps)

## Getting Exercise order onto this df
BestPerformance <- BestPerformance %>%
  left_join(ExerciseTable ,by = "Exercise") %>%
  select(TeamName ,ExerciseId ,Exercise ,Course ,BestPerformance) 


```


FIT Performance
=======================================================================

Column {data-width=200 .sidebar}
-----------------------------------------------------------------------
```{r}

selectInput("TeamInput"
            ,"Select a team:"
            ,choices = TeamName$TeamName
            ,selected = TeamName$TeamName[1])

```



Column {data-width=450 .tabset .tabset-fade}
-----------------------------------------------------------------------

### High Rep Exercises 

```{r}

ReactiveCourseHighReps <- reactive({
  CourseReps %>%
    filter(TeamName == input$TeamInput & Exercise %in% HighRepExercises)
})

renderPlot({
  ggplot(ReactiveCourseHighReps() ,aes(x = as.factor(EventId) ,y = Reps ,fill = Course)) +
    geom_col() +
    facet_wrap(~ Exercise) +
    # scale_x_continuous(breaks = pretty_breaks()) +
    scale_y_continuous(limits = c(0 ,MaxHighRep + 10) ,breaks = seq(0 ,MaxHighRep + 10 ,by = 20)) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Event Number") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    scale_fill_manual(values = c("Course 1" = brewer.pal(3 ,"Set1")[1]
                                 ,"Course 2" = brewer.pal(3 ,"Set1")[2]
                                 ,"Course 3" = brewer.pal(3 ,"Set1")[3])) +
    theme_fivethirtyeight()      
})



```


### Low Rep Exercises

```{r}

ReactiveCourseLowReps <- reactive({
  CourseReps %>%
    filter(TeamName == input$TeamInput & Exercise %in% LowRepExercises)
})

renderPlot({
  ggplot(ReactiveCourseLowReps() ,aes(x = as.factor(EventId) ,y = Reps ,fill = Course)) +
    geom_col() +
    facet_wrap(~ Exercise) +
    # scale_x_continuous(breaks = pretty_breaks()) +
    scale_y_continuous(limits = c(0 ,MaxLowRep + 10) ,breaks = seq(0 ,MaxHighRep + 10 ,by = 15)) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Event Number") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    scale_fill_manual(values = c("Course 1" = brewer.pal(3 ,"Set1")[1]
                                 ,"Course 2" = brewer.pal(3 ,"Set1")[2]
                                 ,"Course 3" = brewer.pal(3 ,"Set1")[3])) +
    theme_fivethirtyeight()      
})



```


### PlankHold

```{r}

ReactivePlankHold <- reactive({
  CourseTimed %>%
    select(-Time) %>%
    filter(TeamName == input$TeamInput & Exercise == 'PlankHold')
})

renderPlot({
  ggplot(ReactivePlankHold() ,aes(x = as.factor(EventId) ,y = TimeInSeconds ,fill = Course)) +
    geom_col() +
    facet_wrap(~ Exercise) +
    geom_hline(yintercept = 480) +
    # scale_x_continuous(breaks = pretty_breaks()) +
    scale_y_continuous(limits = c(0 ,480) ,breaks = seq(0 ,480 ,by = 120) ,labels = c("00:00:00", "02:00:00", "04:00:00", "06:00:00", "08:00:00")) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Event Number") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    scale_fill_manual(values = c("Course 1" = brewer.pal(3 ,"Set1")[1]
                                 ,"Course 2" = brewer.pal(3 ,"Set1")[2]
                                 ,"Course 3" = brewer.pal(3 ,"Set1")[3])) +
    theme_fivethirtyeight()    
})


```


### Timed Exercises

```{r}

ReactiveCourseTimed <- reactive({
  CourseTimed %>%
    select(-Time) %>%
    filter(TeamName == input$TeamInput & Exercise != 'PlankHold')
})

renderPlot({
  ggplot(ReactiveCourseTimed() ,aes(x = as.factor(EventId) ,y = TimeInSeconds ,fill = Course)) +
    geom_col() +
    facet_wrap(~ Exercise) +
    # scale_x_continuous(breaks = pretty_breaks()) +
    scale_y_continuous(limits = c(0 ,100) ,breaks = seq(0 ,100 ,by = 20) ,labels = c("00:00:00", "00:20:00", "00:40:00", "01:00:00", "01:20:00" , "01:40:00")) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Event Number") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    scale_fill_manual(values = c("Course 1" = brewer.pal(3 ,"Set1")[1]
                                 ,"Course 2" = brewer.pal(3 ,"Set1")[2]
                                 ,"Course 3" = brewer.pal(3 ,"Set1")[3])) +
    theme_fivethirtyeight()    
})


```


### Laps

```{r}

ReactiveCourseRunning <- reactive({
  CourseReps %>%
    filter(TeamName == input$TeamInput & Exercise %in% RunningExercises)
})

renderPlot({
  ggplot(ReactiveCourseRunning() ,aes(x = as.factor(EventId) ,y = Reps ,fill = Course)) +
    geom_col() +
    facet_wrap(~ Level) +
    # scale_x_continuous(breaks = pretty_breaks()) +
    scale_y_continuous(limits = c(0 ,MaxLaps + 5)) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Event Number") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    scale_fill_manual(values = c("Course 1" = brewer.pal(3 ,"Set1")[1]
                                 ,"Course 2" = brewer.pal(3 ,"Set1")[2]
                                 ,"Course 3" = brewer.pal(3 ,"Set1")[3])) +
    theme_fivethirtyeight()      
})


```

Column {data-width=350}
-----------------------------------------------------------------------

### Best Performance by Exercise

```{r}
ReactiveBestPerformance <- reactive({
  BestPerformance %>%
    filter(TeamName == input$TeamInput) %>%
    select(ExerciseId ,Course ,Exercise ,BestPerformance) %>%
    arrange(ExerciseId)
})

DT::renderDataTable({
  DT::datatable(ReactiveBestPerformance() ,rownames = FALSE ,options = list(
    bPaginate = FALSE
  ))
})

```


